(function ($) {

    var _cnames = {
        ABW: 'Aruba',
        AFG: 'Afghanistan',
        AGO: 'Angola',
        AIA: 'Anguilla',
        ALA: 'Åland Islands',
        ALB: 'Albania',
        AND: 'Andorra',
        ARE: 'United Arab Emirates',
        ARG: 'Argentina',
        ARM: 'Armenia',
        ASM: 'American Samoa',
        ATA: 'Antarctica',
        ATF: 'French Southern Territories',
        ATG: 'Antigua and Barbuda',
        AUS: 'Australia',
        AUT: 'Austria',
        AZE: 'Azerbaijan',
        BDI: 'Burundi',
        BEL: 'Belgium',
        BEN: 'Benin',
        BES: 'Bonaire, Saint Eustatius and Saba',
        BFA: 'Burkina Faso',
        BGD: 'Bangladesh',
        BGR: 'Bulgaria',
        BHR: 'Bahrain',
        BHS: 'Bahamas',
        BIH: 'Bosnia and Herzegovina',
        BLM: 'Saint Barthélemy',
        BLR: 'Belarus',
        BLZ: 'Belize',
        BMU: 'Bermuda',
        BOL: 'Bolivia, Plurinational State of',
        BRA: 'Brazil',
        BRB: 'Barbados',
        BRN: 'Brunei Darussalam',
        BTN: 'Bhutan',
        BVT: 'Bouvet Island',
        BWA: 'Botswana',
        CAF: 'Central African Republic',
        CAN: 'Canada',
        CCK: 'Cocos (Keeling) Islands',
        CHE: 'Switzerland',
        CHL: 'Chile',
        CHN: 'China',
        CIV: 'Côte d\'Ivoire',
        CMR: 'Cameroon',
        COD: 'Congo, the Democratic Republic of the',
        COG: 'Congo',
        COK: 'Cook Islands',
        COL: 'Colombia',
        COM: 'Comoros',
        CPV: 'Cape Verde',
        CRI: 'Costa Rica',
        CUB: 'Cuba',
        CUW: 'Curaçao',
        CXR: 'Christmas Island',
        CYM: 'Cayman Islands',
        CYP: 'Cyprus',
        CZE: 'Czech Republic',
        DEU: 'Germany',
        DJI: 'Djibouti',
        DMA: 'Dominica',
        DNK: 'Denmark',
        DOM: 'Dominican Republic',
        DZA: 'Algeria',
        ECU: 'Ecuador',
        EGY: 'Egypt',
        ERI: 'Eritrea',
        ESH: 'Western Sahara',
        ESP: 'Spain',
        EST: 'Estonia',
        ETH: 'Ethiopia',
        FIN: 'Finland',
        FJI: 'Fiji',
        FLK: 'Falkland Islands (Malvinas)',
        FRA: 'France',
        FRO: 'Faroe Islands',
        FSM: 'Micronesia, Federated States of',
        GAB: 'Gabon',
        GBR: 'United Kingdom',
        GEO: 'Georgia',
        GGY: 'Guernsey',
        GHA: 'Ghana',
        GIB: 'Gibraltar',
        GIN: 'Guinea',
        GLP: 'Guadeloupe',
        GMB: 'Gambia',
        GNB: 'Guinea-Bissau',
        GNQ: 'Equatorial Guinea',
        GRC: 'Greece',
        GRD: 'Grenada',
        GRL: 'Greenland',
        GTM: 'Guatemala',
        GUF: 'French Guiana',
        GUM: 'Guam',
        GUY: 'Guyana',
        HKG: 'Hong Kong',
        HMD: 'Heard Island and McDonald Islands',
        HND: 'Honduras',
        HRV: 'Croatia',
        HTI: 'Haiti',
        HUN: 'Hungary',
        IDN: 'Indonesia',
        IMN: 'Isle of Man',
        IND: 'India',
        IOT: 'British Indian Ocean Territory',
        IRL: 'Ireland',
        IRN: 'Iran, Islamic Republic of',
        IRQ: 'Iraq',
        ISL: 'Iceland',
        ISR: 'Israel',
        ITA: 'Italy',
        JAM: 'Jamaica',
        JEY: 'Jersey',
        JOR: 'Jordan',
        JPN: 'Japan',
        KAZ: 'Kazakhstan',
        KEN: 'Kenya',
        KGZ: 'Kyrgyzstan',
        KHM: 'Cambodia',
        KIR: 'Kiribati',
        KNA: 'Saint Kitts and Nevis',
        KOR: 'Korea, Republic of',
        KWT: 'Kuwait',
        LAO: 'Lao People\'s Democratic Republic',
        LBN: 'Lebanon',
        LBR: 'Liberia',
        LBY: 'Libyan Arab Jamahiriya',
        LCA: 'Saint Lucia',
        LIE: 'Liechtenstein',
        LKA: 'Sri Lanka',
        LSO: 'Lesotho',
        LTU: 'Lithuania',
        LUX: 'Luxembourg',
        LVA: 'Latvia',
        MAC: 'Macao',
        MAF: 'Saint Martin (French part)',
        MAR: 'Morocco',
        MCO: 'Monaco',
        MDA: 'Moldova, Republic of',
        MDG: 'Madagascar',
        MDV: 'Maldives',
        MEX: 'Mexico',
        MHL: 'Marshall Islands',
        MKD: 'Macedonia, the former Yugoslav Republic of',
        MLI: 'Mali',
        MLT: 'Malta',
        MMR: 'Myanmar',
        MNE: 'Montenegro',
        MNG: 'Mongolia',
        MNP: 'Northern Mariana Islands',
        MOZ: 'Mozambique',
        MRT: 'Mauritania',
        MSR: 'Montserrat',
        MTQ: 'Martinique',
        MUS: 'Mauritius',
        MWI: 'Malawi',
        MYS: 'Malaysia',
        MYT: 'Mayotte',
        NAM: 'Namibia',
        NCL: 'New Caledonia',
        NER: 'Niger',
        NFK: 'Norfolk Island',
        NGA: 'Nigeria',
        NIC: 'Nicaragua',
        NIU: 'Niue',
        NLD: 'Netherlands',
        NOR: 'Norway',
        NPL: 'Nepal',
        NRU: 'Nauru',
        NZL: 'New Zealand',
        OMN: 'Oman',
        PAK: 'Pakistan',
        PAN: 'Panama',
        PCN: 'Pitcairn',
        PER: 'Peru',
        PHL: 'Philippines',
        PLW: 'Palau',
        PNG: 'Papua New Guinea',
        POL: 'Poland',
        PRI: 'Puerto Rico',
        PRK: 'Korea, Democratic People\'s Republic of',
        PRT: 'Portugal',
        PRY: 'Paraguay',
        PSE: 'Palestinian Territory, Occupied',
        PYF: 'French Polynesia',
        QAT: 'Qatar',
        REU: 'Réunion',
        ROU: 'Romania',
        RUS: 'Russian Federation',
        RWA: 'Rwanda',
        SAU: 'Saudi Arabia',
        SDN: 'Sudan',
        SEN: 'Senegal',
        SGP: 'Singapore',
        SGS: 'South Georgia and the South Sandwich Islands',
        SHN: 'Saint Helena, Ascension and Tristan da Cunha',
        SJM: 'Svalbard and Jan Mayen',
        SLB: 'Solomon Islands',
        SLE: 'Sierra Leone',
        SLV: 'El Salvador',
        SMR: 'San Marino',
        SOM: 'Somalia',
        SPM: 'Saint Pierre and Miquelon',
        SRB: 'Serbia',
        STP: 'Sao Tome and Principe',
        SUR: 'Suriname',
        SVK: 'Slovakia',
        SVN: 'Slovenia',
        SWE: 'Sweden',
        SWZ: 'Swaziland',
        SXM: 'Sint Maarten (Dutch part)',
        SYC: 'Seychelles',
        SYR: 'Syrian Arab Republic',
        TCA: 'Turks and Caicos Islands',
        TCD: 'Chad',
        TGO: 'Togo',
        THA: 'Thailand',
        TJK: 'Tajikistan',
        TKL: 'Tokelau',
        TKM: 'Turkmenistan',
        TLS: 'Timor-Leste',
        TON: 'Tonga',
        TTO: 'Trinidad and Tobago',
        TUN: 'Tunisia',
        TUR: 'Turkey',
        TUV: 'Tuvalu',
        TWN: 'Taiwan, Province of China',
        TZA: 'Tanzania, United Republic of',
        UGA: 'Uganda',
        UKR: 'Ukraine',
        UMI: 'United States Minor Outlying Islands',
        URY: 'Uruguay',
        USA: 'United States',
        UZB: 'Uzbekistan',
        VAT: 'Holy See (Vatican City State)',
        VCT: 'Saint Vincent and the Grenadines',
        VEN: 'Venezuela, Bolivarian Republic of',
        VGB: 'Virgin Islands, British',
        VIR: 'Virgin Islands, U.S.',
        VNM: 'Viet Nam',
        VUT: 'Vanuatu',
        WLF: 'Wallis and Futuna',
        WSM: 'Samoa',
        YEM: 'Yemen',
        ZAF: 'South Africa',
        ZMB: 'Zambia',
        ZWE: 'Zimbabwe'
    };

    var _cnames_es = {
        ABW: 'Aruba',
        AFG: 'Afganistan',
        AGO: 'Angola',
        AIA: 'Anguilla',
        ALA: 'Islas Aland',
        ALB: 'Albania',
        AND: 'Andorra',
        ARE: 'Emiratos Arabes Unidos',
        ARG: 'Argentina',
        ARM: 'Armenia',
        ASM: 'Samoa Americana',
        ATA: 'Antartica',
        ATF: 'Territorios Franceses del Sur',
        ATG: 'Antigua y Barbuda',
        AUS: 'Australia',
        AUT: 'Austria',
        AZE: 'Azerbaiyán',
        BDI: 'Burundi',
        BEL: 'Belgica',
        BEN: 'Benin',
        BES: 'Bonaire, San Eustaquio y Saba',
        BFA: 'Burkina Faso',
        BGD: 'Bangladesh',
        BGR: 'Bulgaria',
        BHR: 'Bahrein',
        BHS: 'Bahamas',
        BIH: 'Bosnia y Herzegovina',
        BLM: 'San Bartolomé',
        BLR: 'Bielorrusia',
        BLZ: 'Belice',
        BMU: 'Bermuda',
        BOL: 'Bolivia, Estado Plurinacional de',
        BRA: 'Brasil',
        BRB: 'Barbados',
        BRN: 'Brunei Darussalam',
        BTN: 'Bhután',
        BVT: 'Isla Bouvet',
        BWA: 'Botswana',
        CAF: 'República Centroafricana',
        CAN: 'Canadá',
        CCK: 'Islas Cocos (Keeling)',
        CHE: 'Suiza',
        CHL: 'Chile',
        CHN: 'China',
        CIV: 'Côte d\'Ivoire',
        CMR: 'Camerún',
        COD: 'Congo, la República Democrática del',
        COG: 'Congo',
        COK: 'Islas Cook',
        COL: 'Colombia',
        COM: 'Comoras',
        CPV: 'Cabo Verde',
        CRI: 'Costa Rica',
        CUB: 'Cuba',
        CUW: 'Curazao',
        CXR: 'Islas Navidad',
        CYM: 'Islas Caimán',
        CYP: 'Chipre',
        CZE: 'República Checa',
        DEU: 'Alemania',
        DJI: 'Djibouti',
        DMA: 'Dominica',
        DNK: 'Dinamarca',
        DOM: 'República Dominicana',
        DZA: 'Algelia',
        ECU: 'Ecuador',
        EGY: 'Egipto',
        ERI: 'Eritrea',
        ESH: 'Sahara Occidental',
        ESP: 'España',
        EST: 'Estonia',
        ETH: 'Etiopía',
        FIN: 'Finlandia',
        FJI: 'Fiji',
        FLK: 'Islas Malvinas (Falkland)',
        FRA: 'Francia',
        FRO: 'Islas Feroe',
        FSM: 'Micronesia, Estados Federados de',
        GAB: 'Gabón',
        GBR: 'Reino Unido',
        GEO: 'Georgia',
        GGY: 'Guernsey',
        GHA: 'Ghana',
        GIB: 'Gibralta',
        GIN: 'Guinea',
        GLP: 'Guadelupe',
        GMB: 'Gambia',
        GNB: 'Guinea-Bissau',
        GNQ: 'Guinea Ecuatorial',
        GRC: 'Grecia',
        GRD: 'Granada',
        GRL: 'Groenlandia',
        GTM: 'Guatemala',
        GUF: 'Guayana Francesa',
        GUM: 'Guam',
        GUY: 'Guyana',
        HKG: 'Hong Kong',
        HMD: 'Islas Heard Island and McDonald',
        HND: 'Honduras',
        HRV: 'Croacia',
        HTI: 'Haití',
        HUN: 'Hungria',
        IDN: 'Indonesia',
        IMN: 'Isla de Man',
        IND: 'India',
        IOT: 'Territorio Británico del Océano Índico',
        IRL: 'Irlanda',
        IRN: 'Irán, República Islámica de',
        IRQ: 'Irak',
        ISL: 'Islandia',
        ISR: 'Israel',
        ITA: 'Italia',
        JAM: 'Jamaica',
        JEY: 'Jersey',
        JOR: 'Jordan',
        JPN: 'Japón',
        KAZ: 'Kazajstán',
        KEN: 'Kenia',
        KGZ: 'Kirguistán',
        KHM: 'Camboya',
        KIR: 'Kiribati',
        KNA: 'Saint Kitts and Nevis',
        KOR: 'Corea del Sur',
        KWT: 'Kuwait',
        LAO: 'Lao People\'s República Democrática',
        LBN: 'Líbano',
        LBR: 'Liberia',
        LBY: 'Jamahiriya Árabe Libia',
        LCA: 'Santa Lucia',
        LIE: 'Liechtenstein',
        LKA: 'Sri Lanka',
        LSO: 'Lesotho',
        LTU: 'Lituania',
        LUX: 'Luxemburgo',
        LVA: 'Letonia',
        MAC: 'Macao',
        MAF: 'San Martín (parte francesa)',
        MAR: 'Marruecos',
        MCO: 'Monaco',
        MDA: 'Moldova, República de',
        MDG: 'Madagascar',
        MDV: 'Maldivas',
        MEX: 'México',
        MHL: 'Islas Marshal',
        MKD: 'Macedonia, la ex República Yugoslava de',
        MLI: 'Mali',
        MLT: 'Malta',
        MMR: 'Myanmar',
        MNE: 'Montenegro',
        MNG: 'Mongolia',
        MNP: 'Islas Marianas del Norte',
        MOZ: 'Mozambique',
        MRT: 'Mauritania',
        MSR: 'Montserrat',
        MTQ: 'Martinica',
        MUS: 'Mauricio',
        MWI: 'Malawi',
        MYS: 'Malasia',
        MYT: 'Mayotte',
        NAM: 'Namibia',
        NCL: 'Nueva Caledonia',
        NER: 'Niger',
        NFK: 'Islas Norfolk',
        NGA: 'Nigeria',
        NIC: 'Nicaragua',
        NIU: 'Niue',
        NLD: 'Paises Bajos',
        NOR: 'Noruega',
        NPL: 'Nepal',
        NRU: 'Nauru',
        NZL: 'Nueva Zelanda',
        OMN: 'Omán',
        PAK: 'Pakistán',
        PAN: 'Panamá',
        PCN: 'Pitcairn',
        PER: 'Perú',
        PHL: 'Filipinas',
        PLW: 'Palau',
        PNG: 'Papúa Nueva Guinea',
        POL: 'Polonia',
        PRI: 'Puerto Rico',
        PRK: 'Corea Democrática Popular de la República',
        PRT: 'Portugal',
        PRY: 'Paraguay',
        PSE: 'Palestina, Territorio Ocupado',
        PYF: 'Polinesia Francesa',
        QAT: 'Qatar',
        REU: 'Reunión',
        ROU: 'Rumanía',
        RUS: 'Rusia',
        RWA: 'Ruanda',
        SAU: 'Arabia Saudita',
        SDN: 'Sudán',
        SEN: 'Senegal',
        SGP: 'Singapur',
        SGS: 'Georgia del Sur y las Islas Sandwich del Sur',
        SHN: 'Santa Helena, Ascensión y Tristán da Cunha',
        SJM: 'Svalbard y Jan Mayen',
        SLB: 'Solomon Islands',
        SLE: 'Sierra Leona',
        SLV: 'El Salvador',
        SMR: 'San Marino',
        SOM: 'Somalia',
        SPM: 'San Pedro y Miquelón',
        SRB: 'Serbia',
        STP: 'Santo Tomé y Príncipe',
        SUR: 'Surinam',
        SVK: 'Eslovaquia',
        SVN: 'Eslovenia',
        SWE: 'Suecia',
        SWZ: 'Swazilandia',
        SXM: 'Sint Maarten (parte neerlandesa)',
        SYC: 'Seychelles',
        SYR: 'Siria',
        TCA: 'Islas Turcas y Caicos',
        TCD: 'Chad',
        TGO: 'Togo',
        THA: 'Tailandia',
        TJK: 'Tayikistán',
        TKL: 'Tokelau',
        TKM: 'Turkmenistán',
        TLS: 'Timor-Leste',
        TON: 'Tonga',
        TTO: 'Trinidad y Tobago',
        TUN: 'Túnez',
        TUR: 'Turquía',
        TUV: 'Tuvalu',
        TWN: 'Taiwán, Provincia de China',
        TZA: 'Tanzania, República Unida de',
        UGA: 'Uganda',
        UKR: 'Ucrania',
        UMI: 'Estados Unidos Islas menores alejadas',
        URY: 'Uruguay',
        USA: 'Estados Unidos',
        UZB: 'Uzbekistán',
        VAT: 'Santa Sede (Ciudad del Vaticano)',
        VCT: 'San Vicente y las Granadinas',
        VEN: 'Venezuela, República Bolivariana de',
        VGB: 'Islars Virgenes, Británicas',
        VIR: 'Islas Virgenes,, U.S.',
        VNM: 'Viet Nam',
        VUT: 'Vanuatu',
        WLF: 'Wallis and Futuna',
        WSM: 'Samoa',
        YEM: 'Yemen',
        ZAF: 'Sudáfrica',
        ZMB: 'Zambia',
        ZWE: 'Zimbabwe'
    };

    var methods = {
        init: function (options) {
            var opts = $.extend({}, $.fn.countrySelector.defaults, options);

            return this.each(function () {
                var $this = $(this);
                var data = $this.data('countrySelector');
                $this.addClass('country-selector');

                if ($this.is('div')) {
                    $this.find('.cflag').remove();

                    $this.data('countrySelector', {
                        options: opts
                    });

                    var label = $('<span></span>')
                    $.each(opts.countries, function (i, cc) {
                        
                        var cname = _cnames[cc];
                        if (!cname)
                            cname = cc;
                        var div = $("<div></div>")
                            .addClass("cflag " + cc)
                            .attr("title", cname)
                            .click(function () {
                                if ($(this).hasClass('cflag-selected'))
                                    return;
                                $(this).siblings().removeClass('cflag-selected');
                                $(this).addClass('cflag-selected');
                                opts.onSelected.call($this.get(0), cc, cname);
                                label.data('cname', cname).text(cname);
                            })
                            .hover(function () {
                                label.text(cname);
                            }, function () {
                                label.text(label.data('cname'));
                            });
                        if (cc == opts.value) {
                            div.addClass('cflag-selected');
                            label.data('cname', cname).text(cname);
                        }
                        $this.append(div);
                    });
                }
                else if ($this.is('select')) {
                    $this.empty();
                    if(opts.language == 'es'){
                        cnames = _cnames_es;
                    }else{
                       cnames = _cnames; 
                    }

                    $.each(cnames, function (i, cc) {
                        
                        var cname = cnames[cc];
                        if (!cname)
                            cname = cc;
                        if(i === 'ESP'){
                            $this.append('<option  value="' + i + '" ng-selected="ESP" >' + cname + '</option>');
                        }else{
                            $this.append('<option value="' + i + '">' + cname + '</option>');
                        }
                        
                    });
                    $this.change(function () {
                        var cc = $(this).val();
                        opts.onSelected.call(this, $(this).val(), _cnames[cc]);
                    }).val(opts.value);
                }
            });
        },

        value: function (country) {
            if (country) {
                return this.each(function () {
                    $(this).find('.cflag-selected').removeClass('cflag-selected');
                    $(this).find('.cflag').filter(function () { return $(this).data('country') == country; }).addClass('cflag-selected');
                });
            }
            else {
                if (this.length == 0)
                    return null;
                if (this.length == 1)
                    return $(this).find('.cflag-selected').data('country');
                else {
                    var values = [];
                    this.each(function () {
                        values.push($(this).find('.cflag-selected').data('country'));
                    });
                    return values;
                }
            }
        }
    }

    $.fn.countrySelector = function (method) {
        if (methods[method]) {
            return methods[method].apply(this, Array.prototype.slice.call(arguments, 1));
        } else if (typeof method === 'object' || !method) {
            return methods.init.apply(this, arguments);
        } else {
            $.error('Method ' + method + ' does not exist on jQuery.countrySelector');
        }
    }

    $.fn.countrySelector.defaults = {
        countries: [],
        value: null,
        onSelected: function (country, fullname) { }
    };

})(jQuery);